name: sivo

services:
  #Aplicacao Laravel SIVO
  app:
    container_name: sivo_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Linux/Development volume
      - .:/var/www/html
    ports:
      - "8085:80"
    depends_on:
      - postgres
    networks:
      - laravel

  #Banco de Dados Postgres 15 para o SIVO
  postgres:
    image: postgres:16
    container_name: sivo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_sivo
      POSTGRES_USER: sivo
      POSTGRES_PASSWORD: sivo1234
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - laravel
      
  #Mock para o servidor de email - Enviar email para recuperar senha    
  mailpit:
    image: axllent/mailpit
    container_name: sivo_mailpit
    ports:
      - "2525:1025"
      - "8025:8025"
    networks:
      - laravel

networks:
  laravel:

volumes:
  pg_data:

